# Generated by Django 4.2.20 on 2025-05-07 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='conversation_id',
        ),
        migrations.AlterField(
            model_name='message',
            name='index',
            field=models.PositiveIntegerField(help_text='Message order in the conversation'),
        ),
    ]
