# Generated by Django 4.2 on 2025-05-15 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post_owner_name', models.CharField(max_length=100)),
                ('post_title', models.CharField(max_length=200)),
                ('post_content', models.TextField()),
                ('like_list', models.JSONField(default=list)),
            ],
        ),
    ]
