# Generated by Django 4.2 on 2025-05-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_openpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='openpost',
            name='travel_place',
            field=models.CharField(default='', max_length=100),
        ),
    ]
