# Generated by Django 4.2 on 2025-05-15 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_openpost_travel_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='openpost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 15, 14, 36, 31, 983681)),
        ),
    ]
