# Generated by Django 4.2 on 2025-05-15 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_openpost_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openpost',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
