# Generated by Django 5.2.1 on 2025-05-25 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_openpost_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeepSearchConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversationid', models.CharField(max_length=64, unique=True)),
                ('user_id', models.IntegerField()),
                ('destination', models.CharField(max_length=128)),
                ('budget', models.CharField(max_length=128)),
                ('dates', models.CharField(max_length=128)),
                ('preferences', models.TextField()),
                ('tool_results', models.JSONField(blank=True, null=True)),
                ('agent_results', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
