# Generated by Django 5.2.1 on 2025-05-31 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_deepsearchconversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='deepsearchconversation',
            name='startpoint',
            field=models.CharField(default='Beijing', max_length=128),
        ),
    ]
